### ISSUE TITLE
Not possible to follow a channel

### ISSUE THREAD

**Issue by MarkWieczorek** [accumulator/plugin.video.lbry#7]
First, thanks for making this plugin! 

The problem I am having is that it does not appear possible to follow a channel. I have found out how to add a channel to favorites, but even though there is a "followed channels" folder, I can not figure out how to add anything to it! Though adding channels as favorites is a work around, it is not ideal.

I am using Kodi 19 on macos.

**Comment by accumulator** [comment]
If a video is posted in a channel, there should be a context menu (rightclick) option 'Follow @channel' for that video

**Comment by MarkWieczorek** [comment]
Thanks. I figured it out, but for context, here was the problem:

1. Under *search*, I searched for a channel, like `@robbraxmantech`.
2. Using the context menu on the search results, there is only the option to add the channel to favorites, and not to follow.

Also, I note that the search function is inconsistent: I tried to search for the channel `@techlore`, but nothing comes up, even though the channel exists.

And I have a feature request: Would it be possible to add an option to list all the recent videos for the channels you are following?

**Comment by accumulator** [comment]
Ah! Videos and channels are different entities, the context menu of the latter is indeed not having the follow option it should have. 

> Also, I note that the search function is inconsistent: I tried to search for the channel @techlore, but nothing comes up, even though the channel exists.

Yes I've seen that too. The search request is forwarded by lbrynet to a LBRY/Odysee hosted blockchain indexer, which doesn't return all results you would expect. It is configured to handle many requests from many users, and therefore limits complex queries and aborts queries that take more than a few 100ms.

> Would it be possible to add an option to list all the recent videos for the channels you are following?

I would love to add that, but that is currently problematic due to the indexing server limits I described above. It might be possible but it needs tuning the query so the indexer can handle it fast.

**Comment by accumulator** [comment]
Fixed in 8a5eebfe2c51518d0dec3140209f7cb16ec5783e

> And I have a feature request: Would it be possible to add an option to list all the recent videos for the channels you are following?

Thanks to @amacchietto this is now implemented :)
